# Site settings
title: Porrith Suong
header-img: img/home-bg.jpg
email: psuong95@gmail.com
description: "Website of Porrith Suong"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: PorrithSuong
github_username:  ItsJustBlank
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
